---
title: "Figure 6"
author: "yunqi yang"
date: "4/18/2019"
output:
  pdf_document: default
  html_document: default
---

```{r  }

library(BMmultigene)
library(BayesMendel)
library(pracma)
library(maxLik)
library(ggplot2)
library(gridExtra)

# load USC-Stanford summary data 
load("/Users/nicholeyang/Desktop/research2/VUS_paper/data/res_summary.RData")


```


```{r  }

## BRCApro result
brca = val3[,c("BRCA1or2","GenTestTable.Gene.1.gt","Myriad_panel")]
brca_score =  as.numeric(as.character(brca$BRCA1or2)) 
brca1 = brca[-which(is.na(brca_score)), ]

pos = brca1[which(brca1$Myriad_panel=="Positive"),]
pos_brca = pos$BRCA1or2[which(pos$GenTestTable.Gene.1.gt == "BRCA1" | pos$GenTestTable.Gene.1.gt =="BRCA2")]

VUS = brca1[which(brca1$Myriad_panel=="VUS" | brca1$Myriad_panel=="VUS - Suspect Del/ Likely Pathogenic"),]
VUS_brca = VUS$BRCA1or2[which(VUS$GenTestTable.Gene.1.gt == "BRCA1" | VUS$GenTestTable.Gene.1.gt == "BRCA2")]

neg = brca1[which(brca1$Myriad_panel == "Negative"),]
neg_brca = neg$BRCA1or2

  
pos1 = as.numeric(as.character(pos_brca))   ## positive carrier probabilities. 76 
VUS1 = as.numeric(as.character(VUS_brca))   ## VUS 30 
neg1 = as.numeric(as.character(neg_brca))    
```


```{r  }


## transform to logit scale 
x1 = log(pos1/(1-pos1)) ## positive carrier probabilities 
x2 = log(neg1/(1-neg1)) ## negative carrier probabilities 
x3 = log(VUS1/(1-VUS1)) 

upper = max(c(x1, x2, x3))
lower = min(c(x1, x2, x3))

## Get the range of carrier scores in reported VUS group 
  
df1 <- approxfun(density(x1, bw = "sj", from = lower, to = upper))
df2 <- approxfun(density(x2, bw = "sj", from = lower, to = upper))


plot(density(x1))
```

```{r  }


## result on logit scale 

theta =0
lik <- function(pi) sum(log(pi*df1(x3)+(1-pi)*((df2(x3) - theta*df1(x3))/(1-theta))))
  
A = matrix(c(1,-1),byrow = TRUE)
B = c(0,1)
ml <- maxLik(lik, start=0.7, constraints = list(ineqA=A, ineqB=B))
point_estimate1 = summary(ml)$estimate[1]
point_estimate1

```

```{r  }

for (i in c(1:2000))
{
  
  ## random shuffle the data 
  indx <- sample(1:dim(dt)[1], size = dim(dt)[1], replace = TRUE)
  new_dt <- dt[c(indx), ]
  
  ## logit scale carrier probs 
  pos_brca <- new_dt$CarrierProb[new_dt$TestResult == "Positive"]
  neg_brca <- new_dt$CarrierProb[new_dt$TestResult == "Negative"]
  VUS_brca <- new_dt$CarrierProb[new_dt$TestResult == "VUS"]
  
  pos2 = as.numeric(as.character(pos_brca))   
  VUS2 = as.numeric(as.character(VUS_brca))   
  neg2 = as.numeric(as.character(neg_brca))    
  
  ## get the range of logit carrier scores
  
  upper = max(c(pos2, neg2, VUS2))
  lower = min(c(pos2, neg2, VUS2))
  
  df1 <- approxfun(density(pos2, bw = "sj", from = lower, to = upper))
  df2 <- approxfun(density(neg2, bw = "sj", from = lower, to = upper))


  ## Maximum likelihood estimation 
  theta =0
  lik <- function(pi) sum(log(pi*df1(VUS2)+(1-pi)*((df2(VUS2) - theta*df1(VUS2))/(1-theta))))
  
  A = matrix(c(1,-1),byrow = TRUE)
  B = c(0,1)
  ml <- maxLik(lik, start=0.7, constraints = list(ineqA=A, ineqB=B))
  point_estimate[i] = summary(ml)$estimate[1]
  
  ## Calculate PPV 
  PPVs[i, ] = point_estimate[i]*df1(logit_scores)/(point_estimate[i]*df1(logit_scores) + (1-       point_estimate[i])*df2(logit_scores))
  
}

```


```{r  }

mean(point_estimate)
quantile(point_estimate, 0.025)
quantile(point_estimate, 0.975)
hist(point_estimate)

```

############################################
###### positive predictive value calculation
############################################


```{r  }

par(mfrow=c(1,2),oma = c(0, 0, 2, 0))

## range of logit scores = c(min(carrier_score), max(carrier_score))
logit_scores = seq(lower, upper, by = 0.01)
scores = exp(logit_scores)/(1+exp(logit_scores))


ppv = point_estimate1*df1(logit_scores)/(point_estimate1*df1(logit_scores) + (1-point_estimate1)*df2(logit_scores))


plot(scores, ppv, type = "l", ylab = "Positive Predictive Value", xlab = "(a) Carrier Probabilities")
abline( h= 0.8, col = "blue", lty = 2)
abline( h= 0.9, col = "red", lty = 2)


plot(logit_scores, ppv, type = "l", ylab = "Positive Predictive Value", xlab = "(b) Logit Carrier Probabilities")
abline( h= 0.8, col = "blue", lty = 2)
abline( h= 0.9, col = "red", lty = 2)

```


## Bootstrap CI 

```{r  }

logit_scores = seq(lower, upper, by = 0.01)
TestResult <- c(rep('Positive',length(x1)), rep('Negative',length(x2)),  rep('VUS',length(x3)))
CarrierProb <- c(x1, x2, x3)  # on logit scale
dt <- data.frame(cbind(TestResult, CarrierProb))


## replicates 
point_estimate = rep(NA, 2000)
PPVs = matrix(NA, nrow = 2000, ncol = length(logit_scores))

```

```{r  }

for (i in c(1:2000))
{
  
  ## random shuffle the data 
  indx <- sample(1:dim(dt)[1], size = dim(dt)[1], replace = TRUE)
  new_dt <- dt[c(indx), ]
  
  ## logit scale carrier probs 
  pos_brca <- new_dt$CarrierProb[new_dt$TestResult == "Positive"]
  neg_brca <- new_dt$CarrierProb[new_dt$TestResult == "Negative"]
  VUS_brca <- new_dt$CarrierProb[new_dt$TestResult == "VUS"]
  
  pos2 = as.numeric(as.character(pos_brca))   
  VUS2 = as.numeric(as.character(VUS_brca))   
  neg2 = as.numeric(as.character(neg_brca))    
  
  ## get the range of logit carrier scores
  
  upper = max(c(pos2, neg2, VUS2))
  lower = min(c(pos2, neg2, VUS2))
  
  df1 <- approxfun(density(pos2, bw = "sj", from = lower, to = upper))
  df2 <- approxfun(density(neg2, bw = "sj", from = lower, to = upper))


  ## Maximum likelihood estimation 
  theta =0
  
  lik <- function(pi) sum(log(pi*df1(VUS2)+(1-pi)*((df2(VUS2) - theta*df1(VUS2))/(1-theta))))
  
  A = matrix(c(1,-1),byrow = TRUE)
  B = c(0,1)
  ml <- maxLik(lik, start=0.7, constraints = list(ineqA=A, ineqB=B))
  point_estimate[i] = summary(ml)$estimate[1]
  
  ## Calculate PPV 
  PPVs[i, ] = point_estimate[i]*df1(logit_scores)/(point_estimate[i]*df1(logit_scores) + (1-   point_estimate[i])*df2(logit_scores))
  
}


```



```{r  }

setEPS()
postscript("Figure6.eps")


lower_CI <- apply(PPVs, MARGIN = 2, function(x) quantile(x, 0.05, na.rm = TRUE))
upper_CI <- apply(PPVs, MARGIN = 2, function(x) quantile(x, 0.95, na.rm = TRUE))
scores <- exp(logit_scores)/(1+exp(logit_scores))


par(mfrow=c(1,2),oma = c(0, 0, 2, 0))

##
plot(logit_scores, ppv, type = 'l', pch = 19,cex = 0.1, ylab = "Positive Predictive Value", xlab = "(a) Logit Carrier Probabilities")
polygon(c(logit_scores,rev(logit_scores)),c(lower_CI, rev(upper_CI)), col="gray90", border="gray90")
lines(logit_scores, ppv, type = 'l', pch = 19,cex = 0.1, col = "black")
abline( h= 0.8, col = "blue", lty = 2)
abline( h= 0.9, col = "red", lty = 2)

##
plot(scores, ppv, type = 'l', pch = 19,cex = 0.1, ylab = "Positive Predictive Value", xlab = "(b) Carrier Probabilities")
polygon(c(scores,rev(scores)),c(lower_CI, rev(upper_CI)),col="gray90", border="gray90")
lines(scores, ppv, type = 'l', pch = 19,cex = 0.1, col = "black")
abline( h= 0.8, col = "blue", lty = 2)
abline( h= 0.9, col = "red", lty = 2)


dev.off()
```


