---
title: "Figure2-3"
author: "Yunqi Yang"
date: "6/2/2020"
output: html_document
---

```{r  }

summary = function(estimates, true_pi){
  
  mean = mean(estimates)
  lo = quantile(estimates, 0.025)
  up = quantile(estimates, 0.975)
  MSE = sum((estimates - mean)^2)/n
  pbias = 100*sum(estimates - true_pi)/sum(estimates)
  summary_stat = c(mean, lo, up, MSE, pbias)

  return(summary_stat)
}

```


## Fig2.(a)
```{r  }

n = 2000
estimates1 = matrix(NA, ncol = n, nrow  = 3)
type = c("1k", "5k", "1w")

# load estimate results
for (j in 1:3){
  
  file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig2/sample_size/", type[j]), pattern="*.RData"))
  
  for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig2/sample_size/", type[j], '/',file_names[[i]]))
    estimates1[j,i] = point_estimate
  }
}


# result summary
result = matrix(NA, ncol = 5, nrow = 3)
for (i in 1:3){
  result[i, ] = summary(estimates1[i, ], 0.1)
}
```



```{r  }

# save results
rownames(estimates1) = c('1k', '5k', '1w')
write.csv(t(estimates1), file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig2a.csv')

colnames(result) = c("mean", "2.5%CI", "97.5%CI", "MSE", "pBias")
write.csv(result, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/res_fig2a.csv')
```

```{r  }

# estimation results for sample size = 1 million 
n = 50 
res_1m = rep(NA, n)

file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/1m_fam_results/results/no_theta"), pattern="*.RData"))
  
for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/1m_fam_results/results/no_theta", '/',file_names[[i]]))
    res_1m[i] = point_estimate
}

```

```{r  }

res_summary = summary(res_1m, 0.1)

write.csv(res_1m, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig2a_1m.csv')
```



## Fig2.(b)
```{r  }


estimates2 = matrix(NA, ncol = n, nrow = 4)
type = c("pi1", "pi2", "pi3", 'pi4')

for (j in 1:4){
  
  file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig2/true_pi/", type[j]), pattern="*.RData"))
  
  for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig2/true_pi/", type[j], '/',file_names[[i]]))
    estimates2[j,i] = point_estimate
  }
}

```


```{r  }

result = matrix(NA, ncol = 5, nrow = 4)
true_pi = c(0.01, 0.05, 0.1, 0.2)

for (i in 1:4){
  result[i, ] = summary(estimates2[i, ], true_pi[i])
}

```

```{r  }


colnames(result) = c("mean", "2.5%CI", "97.5%CI", "MSE", "pBias")
rownames(estimates2) = c('pi=0.01','pi=0.05', 'pi=0.1', 'pi=0.2')

write.csv(t(estimates2), file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig2b.csv')

write.csv(result, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/res_fig2b.csv')

```




## Fig2.(c)
```{r  }


estimates3 = matrix(NA, ncol = n, nrow = 3)
type = c("pvus1", "pvus2", "pvus3")


for (j in 1:3){
  
  file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig2/pvus/results/", type[j]), pattern="*.RData"))
  
  for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig2/pvus/results/", type[j], '/',file_names[[i]]))
    estimates3[j,i] = point_estimate
  }
}


result = matrix(NA, ncol = 5, nrow = 3)

for (i in 1:3){
  result[i, ] = summary(estimates3[i, ], 0.1)
}
```

```{r  }



colnames(result) = c("mean", "2.5%CI", "97.5%CI", "MSE", "pBias")
rownames(estimates3) = c('pvus=0.1', 'pvus=0.2', 'pvus=0.3')

write.csv(t(estimates3), file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig2c.csv')

write.csv(result, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/res_fig2c.csv')
```


## Figure 2 Plot
```{r  }

setEPS()
postscript("Figure2.eps")

par(mfrow = c(1,3))

boxplot(estimates1[1, ], estimates1[2, ], estimates1[3, ], res_1m, boxwex=0.4, cex.axis =1, col = "lightgrey", xlab = "(a) Sample Size", ylab =expression(hat(pi)), ylim=c(0,0.3))
#mtext("Sample size",1,line=1,at=0, cex=0.6)
mtext("1000",1,line=1,at=1, cex=0.4)
mtext("5000",1,line=1,at=2, cex=0.4)
mtext("10,000",1,line=1,at=3, cex=0.4)
mtext("1,000,000",1,line=1,at=4, cex=0.4)
abline(h=0.1, col="red", lty= 4)


## Fig2.b
boxplot(estimates2[1, ], estimates2[2, ], estimates2[3, ], estimates2[4, ], boxwex=0.4, cex.axis =1, col = "skyblue", xlab = expression(paste("(b) True ", pi)),ylab =expression(hat(pi)), ylim=c(0,0.3))
#mtext(expression(sqrt(MSE)),1,line=1,at=0, cex=0.6)
mtext("0.01",1,line=1,at=1, cex=0.4)
mtext("0.05",1,line=1,at=2, cex=0.4)
mtext("0.1",1,line=1,at=3, cex=0.4)
mtext("0.2",1,line=1,at=4, cex=0.4)


## Fig2.c
boxplot(estimates3[1, ], estimates3[2, ], estimates3[3, ], boxwex=0.4, cex.axis =1, col = "khaki1", xlab = expression(paste("(c) ", P(VUS))),ylab =expression(hat(pi)), ylim=c(0,0.3))       
#mtext("P(vus)",1,line=1,at=0, cex=0.6)
mtext("0.1",1,line=1,at=1, cex=0.4)
mtext("0.2",1,line=1,at=2, cex=0.4)
mtext("0.3",1,line=1,at=3, cex=0.4)
abline(h=0.1, col="red", lty= 4)

dev.off()
```


## Fig3.(a)
```{r  }

n = 2000
estimates4 = matrix(NA, ncol = n, nrow  = 3)
type = c("1k_neg", "5k_neg", "1w_neg")

for (j in 1:3){
  
    file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig3/sample_size/results/", type[j])), pattern = '*.RData')
  
  for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig3/sample_size/results/", type[j], '/',file_names[[i]]))
    estimates4[j,i] = point_estimate
  }
}



result = matrix(NA, ncol = 5, nrow = 3)
for (i in 1:3){
  result[i, ] = summary(estimates4[i, ], 0.1)
}
```

```{r  }
rownames(estimates4) = c('1k', '5k', '1w')
write.csv(t(estimates4), file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig3a.csv')

colnames(result) = c("mean", "2.5%CI", "97.5%CI", "MSE", "pBias")
write.csv(result, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/res_fig3a.csv')
```

```{r  }

n = 50 
res_1m = rep(NA, n)

file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/1m_fam_results/results/with_theta"), pattern="*.RData"))
  
for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/1m_fam_results/results/with_theta", '/',file_names[[i]]))
    res_1m[i] = point_estimate
}

```

```{r  }

res_summary = summary(res_1m, 0.1)

write.csv(res_1m, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig3a_1m.csv')
```




## Fig3.(b)
```{r  }

n = 2000
estimates5 = matrix(NA, ncol = n, nrow  = 4)
type = c("theta1", "theta2", "theta3", 'theta4')

for (j in 1:4){
  
    file_names=as.list(dir(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig3/vary_theta/results/", type[j])), pattern = '*.RData')
  
  for(i in 1:n){
    load(paste0("/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/Fig3/vary_theta/results/", type[j], '/',file_names[[i]]))
    estimates5[j,i] = point_estimate
  }
}


result = matrix(NA, ncol = 5, nrow = 4)

for (i in 1:4){
  result[i, ] = summary(estimates5[i, ], 0.1)
}
```

```{r  }
rownames(estimates5) = c('theta=0.01','theta=0.05','theta=0.1','theta=0.2')
write.csv(t(estimates5), file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/Fig3b.csv')

colnames(result) = c("mean", "2.5%CI", "97.5%CI", "MSE", "pBias")
write.csv(result, file = '/Users/nicholeyang/Desktop/research2/VUSpaper_Revision/new_sim_results/result_summary/res_fig3b.csv')
```


```{r  }

setEPS()
postscript("Figure3.eps")


par(mfrow = c(1,2))

## Fig3.a

boxplot(estimates4[1, ], estimates4[2, ], estimates4[3, ], res_1m, boxwex=0.4, cex.axis =1, col = "lightgrey", xlab = "(a) Sample Size",ylab =expression(hat(pi)), ylim=c(0,0.3))
mtext("",1,line=1,at=0, cex=0.6)
mtext("1,000",1,line=1,at=1, cex=0.6)
mtext("5,000",1,line=1,at=2, cex=0.6)
mtext("10,000",1,line=1,at=3, cex=0.6)
mtext("1,000,000",1,line=1,at=4, cex=0.6)
abline(h=0.1, col="red", lty= 4)



boxplot(estimates5[1, ], estimates5[2, ], estimates5[3, ], estimates5[4, ], boxwex=0.4, cex.axis =1, col = "skyblue", 
        xlab = expression(paste("(b) ", theta)), ylab =expression(hat(pi)),ylim=c(0,0.3))
mtext("",1,line=1,at=0, cex=0.6)
mtext("0.01",1,line=1,at=1, cex=0.6)
mtext("0.05",1,line=1,at=2, cex=0.6)
mtext("0.1",1,line=1,at=3, cex=0.6)
mtext("0.2",1,line=1,at=4, cex=0.6)
abline(h=0.1, col="red", lty= 4)

dev.off()
```
